version: "3.8"
services:
  app:
    build:
      context: .
    image: mds-akcije-app
    container_name: mds-akcije-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mds_tz_akcije
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
      image: mysql:8.0
      container_name: mysql-db
      ports:
        - "3306:3306"
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mds_tz_akcije
      volumes:
        - ./mds_tz_akcije.sql:/docker-entrypoint-initdb.d/mds_tz_akcije.sql

volumes:
  db_data:
